Repository dsd-cohort-team-corgi/frontend, pull requests merged in 2025-07, with the labels that each got.

#16 Home page hero setup
  app/page.tsx
  components/HelloWorld.tsx
  package-lock.json
  public/HomePageHeroImage.png
Labels: frontend

#21 Feat: Provider Detail Page Created
  .prettierrc
  app/layout.tsx
  app/providers/[slug]/[providerId]/page.tsx
  app/providers/[slug]/layout.tsx
  app/providers/[slug]/page.tsx
  components/IconServiceTime.tsx
  components/ProviderOverallRatingInfo.tsx
  components/ReviewCard.tsx
  components/ReviewStarRating.tsx
  components/StyledAsButton.tsx
  components/icons/FullStar.tsx
  package-lock.json
  package.json
  public/default-profile-image.png
  tailwind.config.ts
  utils/convertDateToTimeFromNow.tsx
  utils/emptyOrFullStar.tsx
Labels: frontend

#42 Feat: Adding Calendar and Time Slot Functionality Closes Issue #13
  app/providers/[slug]/[providerId]/page.tsx
  components/Calendar/AvailableTimeSlots.tsx
  components/Calendar/Calendar.tsx
  components/IconServiceTime.tsx
  global.d.ts
  package-lock.json
  package.json
  utils/calculateBusyTimeSlots.ts
  utils/convertDateToTimeFromNow.ts
  utils/convertTimeFrom24To12Hours.ts
  utils/generateTimeSlots.ts
  utils/getValidAppointmentStartTimes.ts
  utils/handleClickToggleOffOrChangeState.ts
Labels: enhancement, frontend

#48 Feature: Added Test Page to View Auth Bearer Token
  app/test/page.tsx
Labels: enhancement

#50 Feature: Booking Details and Checkout Page
  app/checkout/page.tsx
  components/IconLeftTwoTextRight.tsx
  components/stripe/BookingCheckoutPage.tsx
  package-lock.json
  package.json
Labels: frontend
